version: '3.7'
services:
  ####################################################################################################
  # Creating container MySQL
  ####################################################################################################
  mysql_microservice:
    container_name: ${MYSQL_NAME}
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        - TAG=${MYSQL_TAG}
        - EXP=${MYSQL_CONTAINER_PORT}
    volumes:
        - mysql_dump:/var/lib/mysql
    networks:
      - net_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  ####################################################################################################
  # The Redis Server
  ####################################################################################################
  redis_microservice:
    container_name: ${REDIS_NAME}
    build:
      context: .
      dockerfile: redis/Dockerfile
      args:
        - TAG=${REDIS_TAG}
        - EXP=${REDIS_CONTAINER_PORT}
    volumes:
        - redis_dump:/data
    networks:
      - net_db

  # Use it with command: docker-compose run redis-cli
  redis-cli_microservice:
    container_name: ${REDIS_CLI_NAME}
    image: redis:${REDIS_TAG}
    networks:
      - net_db
    links:
      - ${REDIS_NAME}
    command: redis-cli -h redis

  ####################################################################################################
  # The Application
  ####################################################################################################
  backend_microservice:
    container_name: ${BACKEND_NAME}
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - TAG=${BACKEND_TAG}
        - EXP=${BACKEND_CONTAINER_PORT}
    working_dir: /var/www
    volumes:
      - ../application:/var/www
    links:
      - ${MYSQL_NAME}
      - ${REDIS_NAME}
    networks:
      - net_webserver
      - net_backend
      - net_db

  ####################################################################################################
  # The Web Server
  ####################################################################################################
  webserver_microservice:
    container_name: ${WEBSERVER_NAME}
    build:
      context: .
      dockerfile: webserver/Dockerfile
      args:
        - TAG=${WEBSERVER_TAG}
        - EXP=${WEBSERVER_CONTAINER_PORT}
    working_dir: /var/www
    ports:
      - "${WEBSERVER_HOST_PORT}:${WEBSERVER_CONTAINER_PORT}"
    networks:
      - net_webserver
      - net_proxy_gateway
    depends_on:
      - ${BACKEND_NAME}

volumes:
  mysql_dump:
  redis_dump:

networks:
  net_webserver: {}
  net_backend: {}
  net_db: {}
  net_proxy_gateway:
    external: true