version: '3.7'
services:
  ####################################################################################################
  # Creating container MySQL
  ####################################################################################################
  mysql:
    container_name: ${MYSQL_NAME}
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        - TAG=${MYSQL_TAG}
    ports:
      - "3306:3306"
    expose:
        - 3306
    volumes:
        - mysql_dump:/var/lib/mysql
    networks:
      - net_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}


  ####################################################################################################
  # The Redis Server
  ####################################################################################################
  redis:
    container_name: ${REDIS_NAME}
    build:
      context: .
      dockerfile: redis/Dockerfile
      args:
        - TAG=${REDIS_TAG}
    expose:
        - 6379
    volumes:
        - redis_dump:/data
    networks:
      - net_db

  # Use it with command: docker-compose run redis-cli
  redis-cli:
    container_name: ${REDIS_NAME}-cli
    image: redis:${REDIS_TAG}
    networks:
      - net_db
    links:
      - redis
    command: redis-cli -h redis

  ####################################################################################################
  # The Application
  ####################################################################################################
  backend:
    container_name: ${BACKEND_NAME}
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - TAG=${BACKEND_TAG}
    working_dir: /var/www
    expose:
        - 9000
    volumes:
      - ../application:/var/www
    links:
      - mysql
      - redis
    networks:
      - net_webserver
      - net_backend
      - net_db

  ####################################################################################################
  # The Web Server
  ####################################################################################################
  webserver:
    container_name: ${WEBSERVER_NAME}
    build:
      context: .
      dockerfile: webserver/Dockerfile
      args:
        - TAG=${WEBSERVER_TAG}
    working_dir: /var/www
    ports:
      - "80:80"
    networks:
      - net_webserver
      - net_proxy_gateway
    depends_on:
      - backend

volumes:
  mysql_dump:
  redis_dump:

networks:
  net_webserver: {}
  net_backend: {}
  net_db: {}
  net_proxy_gateway:
    external: true