version: '3.7'
services:
  ####################################################################################################
  # Creating container MySQL
  ####################################################################################################
  mysql_microservice:
    container_name: ${MYSQL_NAME}
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        - TAG=${MYSQL_TAG}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - mysql_dump_microservice:/var/lib/mysql
    networks:
      - net_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  ####################################################################################################
  # The Redis Server
  ####################################################################################################
  redis_microservice:
    container_name: ${REDIS_NAME}
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - TAG=${REDIS_TAG}
    expose:
      - ${REDIS_CONTAINER_PORT}
    volumes:
      - redis_dump_microservice:/data
    networks:
      - net_db

  # Use it with command: docker-compose run redis-cli
  redis-cli_microservice:
    container_name: ${REDIS_CLI_NAME}
    image: redis:${REDIS_TAG}
    networks:
      - net_db
    links:
      - ${REDIS_NAME}
    command: redis-cli -h redis

  ####################################################################################################
  # The Application
  ####################################################################################################
  backend_microservice:
    container_name: ${BACKEND_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - TAG=${BACKEND_TAG}
    expose:
      - ${BACKEND_CONTAINER_PORT}
    environment:
      - COMPOSER=${BACKEND_ENV_COMPOSER}
    working_dir: /var/www
    volumes:
      - ../application:/var/www
    networks:
      - net_webserver
      - db_global

  ####################################################################################################
  # The Web Server
  ####################################################################################################
  webserver_microservice:
    container_name: ${WEBSERVER_NAME}
    build:
      context: ./webserver
      dockerfile: Dockerfile
      args:
        - TAG=${WEBSERVER_TAG}
    expose:
      - ${WEBSERVER_CONTAINER_PORT}
    working_dir: /var/www
    networks:
      - net_webserver
      - net_proxy_gateway
    depends_on:
      - ${BACKEND_NAME}

volumes:
  mysql_dump_microservice:
  redis_dump_microservice:

networks:
  net_webserver: {}
  db_global:
    external: true
  net_proxy_gateway:
    external: true